// SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

package gvproxy

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"

	"github.com/stacklok/propolis/net"
)

const (
	// guestIP is the default IP assigned to the guest VM by gvproxy.
	guestIP = "192.168.127.2"

	// socketWaitTimeout is how long we wait for the gvproxy socket to appear.
	socketWaitTimeout = 10 * time.Second

	// socketPollInterval is the interval between polls for the socket file.
	socketPollInterval = 100 * time.Millisecond
)

// Provider is a [net.Provider] backed by gvproxy.
type Provider struct {
	binaryPath string
	sockPath   string
	configPath string
	pid        int
	cmd        *exec.Cmd
	dataDir    string
}

// New creates a new gvproxy Provider. It locates the gvproxy binary
// on the system PATH. The dataDir is used to store the Unix socket
// and configuration files.
func New(dataDir string) *Provider {
	binaryPath, err := exec.LookPath("gvproxy")
	if err != nil {
		// Store empty path; Start will fail with a clear error.
		slog.Warn("gvproxy binary not found in PATH", "error", err)
	}

	return &Provider{
		binaryPath: binaryPath,
		sockPath:   filepath.Join(dataDir, "gvproxy.sock"),
		configPath: filepath.Join(dataDir, "gvproxy.yaml"),
		dataDir:    dataDir,
	}
}

// Start launches gvproxy as a detached process with the given configuration.
// It writes a YAML config file and starts gvproxy pointing at that config,
// then waits for the Unix socket to appear before returning.
func (p *Provider) Start(ctx context.Context, cfg net.Config) error {
	if p.binaryPath == "" {
		return fmt.Errorf("gvproxy binary not found: ensure gvproxy is installed and in PATH")
	}

	if err := os.MkdirAll(p.dataDir, 0o700); err != nil {
		return fmt.Errorf("create gvproxy data dir: %w", err)
	}

	// Clean up any stale socket from a previous run.
	_ = os.Remove(p.sockPath)

	// Write the gvproxy YAML configuration.
	if err := p.writeConfig(cfg); err != nil {
		return fmt.Errorf("write gvproxy config: %w", err)
	}

	// Build gvproxy command arguments.
	args := []string{
		"-listen", "unix://" + p.sockPath,
		"-listen-qemu", "unix://" + p.sockPath + ".qemu",
	}

	// Add port forwards.
	for _, fwd := range cfg.Forwards {
		args = append(args, "-forward",
			fmt.Sprintf("tcp://127.0.0.1:%d/%s:%d",
				fwd.Host, guestIP, fwd.Guest))
	}

	logFile := filepath.Join(cfg.LogDir, "gvproxy.log")

	lf, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return fmt.Errorf("open gvproxy log file %s: %w", logFile, err)
	}

	p.cmd = exec.CommandContext(ctx, p.binaryPath, args...)
	p.cmd.Stdout = lf
	p.cmd.Stderr = lf
	p.cmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid: true, // Detach from parent process group.
	}

	slog.Info("starting gvproxy",
		"binary", p.binaryPath,
		"socket", p.sockPath,
		"forwards", len(cfg.Forwards),
	)

	if err := p.cmd.Start(); err != nil {
		_ = lf.Close()
		return fmt.Errorf("start gvproxy: %w", err)
	}

	// Close the log file handle in the parent; the child owns it now.
	_ = lf.Close()

	p.pid = p.cmd.Process.Pid
	slog.Info("gvproxy started", "pid", p.pid)

	// Wait for the socket to appear.
	if err := p.waitForSocket(ctx); err != nil {
		p.Stop()
		return fmt.Errorf("waiting for gvproxy socket: %w", err)
	}

	return nil
}

// SocketPath returns the path to the gvproxy Unix domain socket.
func (p *Provider) SocketPath() string {
	return p.sockPath
}

// PID returns the gvproxy process ID, or 0 if not running.
func (p *Provider) PID() int {
	return p.pid
}

// Stop terminates the gvproxy process.
func (p *Provider) Stop() {
	if p.cmd == nil || p.cmd.Process == nil {
		return
	}

	slog.Info("stopping gvproxy", "pid", p.pid)

	if err := p.cmd.Process.Signal(syscall.SIGTERM); err != nil {
		slog.Warn("failed to send SIGTERM to gvproxy", "pid", p.pid, "error", err)
		// Try harder.
		_ = p.cmd.Process.Kill()
	}

	// Best-effort wait to reap the process.
	_ = p.cmd.Wait()

	// Clean up the socket file.
	_ = os.Remove(p.sockPath)

	p.pid = 0
	p.cmd = nil
}

// writeConfig writes the gvproxy YAML configuration file.
func (p *Provider) writeConfig(cfg net.Config) error {
	var content string

	content = "# Auto-generated by propolis - do not edit\n"
	content += "gateway: 192.168.127.1\n"
	content += "guest: " + guestIP + "\n"
	content += "subnet: 192.168.127.0/24\n"
	content += "forwards:\n"

	for _, fwd := range cfg.Forwards {
		content += fmt.Sprintf("  - host_port: %d\n    guest_port: %d\n    host: 127.0.0.1\n    guest: %s\n",
			fwd.Host, fwd.Guest, guestIP)
	}

	if err := os.WriteFile(p.configPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write config to %s: %w", p.configPath, err)
	}

	return nil
}

// waitForSocket polls until the gvproxy Unix socket file appears on disk.
func (p *Provider) waitForSocket(ctx context.Context) error {
	deadline := time.After(socketWaitTimeout)
	ticker := time.NewTicker(socketPollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return fmt.Errorf("context cancelled while waiting for gvproxy socket: %w", ctx.Err())
		case <-deadline:
			return fmt.Errorf("timeout after %s waiting for gvproxy socket at %s", socketWaitTimeout, p.sockPath)
		case <-ticker.C:
			if _, err := os.Stat(p.sockPath); err == nil {
				slog.Debug("gvproxy socket ready", "path", p.sockPath)
				return nil
			}

			// Check if the process died.
			if p.cmd.ProcessState != nil {
				return fmt.Errorf("gvproxy exited prematurely with code %d",
					p.cmd.ProcessState.ExitCode())
			}
		}
	}
}

